services:
  mysql:
    image: mysql:8.0
    container_name: mysql-product-api
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: products
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
  redis:
    image: redis:7.2-alpine
    container_name: redis-product-api
    ports:
      - "6379:6379"
    restart: unless-stopped
  product-api:
    build: .
    container_name: product-api
    ports:
      - "8080:8080"
    environment:
      - ENV=prod
      - DATABASE_URL=jdbc:mysql://mysql:3306/products
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=pass
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mysql
      - redis
    restart: unless-stopped

volumes:
  mysql_data: