spring:
    datasource:
        url: jdbc:mysql://localhost:3306/products
        username: root
        password: pass
        driver-class-name: com.mysql.cj.jdbc.Driver
    data.redis:
        host: localhost
        port: 6379
    cache:
        type: redis
    jpa:
        hibernate:
            ddl-auto: update
        defer-datasource-initialization: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
                show_sql: true
    sql:
        init:
            mode: always

